# Generated by Django 5.1.4 on 2024-12-22 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_manufacturer_publisher_game_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='game',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task1.manufacturer'),
            preserve_default=False,
        ),
    ]
