# Generated by Django 5.1.4 on 2024-12-22 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_remove_game_manufacturer_game_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.publisher'),
        ),
    ]
